name: Go
on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v5
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: wsl2-ssh-pageant.exe
        # Directory containing files to upload
        path: wsl2-ssh-pageant.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: ${{ success() && github.ref_type == 'tag' }}
      with:
        tag_name: ${{ github.ref_name }}
        files: wsl2-ssh-pageant.exe
        generate_release_notes: true
